name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - uses: xt0rted/stylelint-problem-matcher@v1
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - name: Yarn install
        run: yarn install --frozen-lockfile
      # ::add-matcher is documented here:
      # https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
      - name: Set up percy problem matcher
        run: echo "::add-matcher::${GITHUB_WORKSPACE}/.github/percy.json"
      - name: Run Tests
        run: yarn percy exec -- yarn test:only
        env:
          EMBER_ENV: test
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_ENABLE: '1'
          COVERAGE: 'true'
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
