name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Set up percy problem matcher
        run: echo "::add-matcher::${GITHUB_WORKSPACE}/.github/percy.json"
      - name: Run Tests
        run: yarn percy exec --parallel -- yarn test:only
        env:
          EMBER_ENV: test
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_ENABLE: '1'
          # By default this is just the run_id, adding the run_attempt prevents an error when jobs are re-run.
          PERCY_PARALLEL_NONCE: ${{github.run_id}}-${{github.run_attempt}}
          # The number of parallel nodes being run so Percy can group the test builds
          PERCY_PARALLEL_TOTAL: '2'
          COVERAGE: 'true'
